language: node_js
node_js: stable
script:language: node_js
node_js: stable
script:
    - yarn
    - yarn test
    - yarn build

after_success: yarn coverage

deploy:
  provider: heroku
  api_key:
    secure: YcqMNYNZ7y6uC5BJ5JBUQX783PxmvewXBP+5F2oQzCrdvvB3+EJR4+FvS+/+6v6klXenCbwkqx+XwExWLH4c/3JyZVRyITfIKRPOPr20QclYel0lmyK1jVzLjyYAiKpK5wP6wuFZrKYVCqHUllS1wYv0zwuskhKyaLkW2JAvZMo=
  app: react-shadow
  on:
    repo: Wildhoney/ReactShadow
  skip_cleanup: true
